### ISSUE TITLE
Shift + Enter inside list item

### ISSUE THREAD

**Issue by adjourn** [ConvertKit/slate-plugins#16]
Not sure if bug or not, i.e if we or this plugin should prevent `Shift+Enter` event..

If caret is in `list-item-child` which is not empty and you press `Shift+Enter`, new `list-item-child` with zero-width element is created and appended to same line and you need to press `Shift+Enter` again to make another `list-item-child` which finally appreas on next line.

I've found at least 3 bugs (and would probably find more) related to `Shift+Enter` and `list-item-child` which leads me to belive that `Shift+Enter` and multi-line list items are not intended features..

I tried the [demo in documentation](https://convertkit-slate-plugins.netlify.com/plugins/slate-lists).

Awesome plugins by the way! I might use the list one if this issue gets resolved.

**Comment by brendancarney** [comment]
Thanks for the issue @adjourn. Yes, this is not intentional. I'm thinking this should soft-break instead, which would be a quick fix.

**Comment by adjourn** [comment]
Soft-break should be just fine. 

I've tried to implement block list-items which can contain anything but normally it's not needed and while I got basic functionality to work, there were lots of bugs, caveats, validation overhead and spaghetti code. Not worth the effort for generic list plugin in my opinion.

**Comment by brendancarney** [comment]
I had to switch `list-item-child` to render a `div` to fix a different bug, but it could also be the solution to this one as well. https://github.com/ConvertKit/slate-plugins/pull/17

Instead of soft break, we could allow multiple `list-item-child` nodes, and let slate do its default behavior of adding a new one on enter. Soft break could be implemented outside of the plugin if someone wanted it.

**Comment by adjourn** [comment]
Was the change related to [this](https://github.com/ianstormtaylor/slate/issues/2500)? I saw the discussion in Slack.

**Comment by brendancarney** [comment]
Sort of, in that it helped me find it. There were some odd behaviors with cursor placement when deleting and using spans. I haven't had much time to look into that issue yet, but I think it's mostly because of it being the only node in the document, and there is no default behavior to change it to anything else. It does seem odd though.

**Comment by brendancarney** [comment]
After playing with it a little more, I decided that soft break is probably the way to go for now. It will be easier to open up the structure a little bit later than it would be to restrict it later, so I'd rather start more restrictive.

**Comment by brendancarney** [comment]
Fixed in `0.2.0`

**Comment by amirphp7** [comment]
how to set getItemDepth up to 3 please, advice
