### ISSUE TITLE
slate-keymap: drive-by what-if analysis

### ISSUE THREAD

**Issue by wmertens** [ConvertKit/slate-plugins#7]
I just found your repo and I like the concept of slate-keymap. I looked at the code and have two comments:

* Would it not be better to map hotkeys to a canonical string, and use a map to match handlers? Now each keystroke performs a linear search.
* How about string handlers that just call an editor command? See https://docs.slatejs.org/guides/plugins#register-commands-and-queries - E.g. `"ctrl+i": 'insertImage'`

**Comment by brendancarney** [comment]
Thanks for checking it out @wmertens! 

> * Would it not be better to map hotkeys to a canonical string, and use a map to match handlers? Now each keystroke performs a linear search.

Thinking about this to make sure I follow: So a user pressing "ctrl" and "i" would map to the string "ctrl+i", and then we would check if that key is in a map? If so, for things like pressing "ctrl", "shift", and "i",  "ctrl+shift+i" and "shift+ctrl+i" would both be valid.  So we would have to do some normalization there. I'd have to see what that ends up looking like in code to understand more. Let me know if you meant something different. 

> * How about string handlers that just call an editor command? See https://docs.slatejs.org/guides/plugins#register-commands-and-queries - E.g. `"ctrl+i": 'insertImage'`

I like this. I started with the function because it was more flexible, but I think we can and should support both. So these would both be valid:
```
{
  "ctrl+i": "insertImage",
  "mod+a": (event, editor) => editor.selectAll()
}
```

Is that what you had in mind?

**Comment by wmertens** [comment]
Correct on both :)

I think is-hotkey has some normalization built in too

**Comment by brendancarney** [comment]
Great! Well I'm 100% sold on adding the string command support, as that will cleanup some code in the upcoming `slate-lists`. Let me know if you want to add it, and if not, I'll go ahead and do it. 

And good point about is-hotkey, I'll check out how it's done there.

**Comment by wmertens** [comment]
No, you can do it, thank you :)

It looks like is-hotkey can parse keys and then it compares the resulting object. I think it will need to have a `stringifyKey` method added.

**Comment by brendancarney** [comment]
Created a PR https://github.com/ConvertKit/slate-plugins/pull/8 for the string command idea. Let me know what you think. I'm going to have my team take a look as well. Thanks for the suggestion!

**Comment by brendancarney** [comment]
Thanks again for taking a look @wmertens. I'm going to close out this issue. I'll probably wait on the optimization until I or someone else runs into issues with it.
